//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Solid.Arduino {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Solid.Arduino.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert non-BCD data..
        /// </summary>
        internal static string ArgumentEx_CannotConvertBcd {
            get {
                return ResourceManager.GetString("ArgumentEx_CannotConvertBcd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Channel number must be between 0 and 15..
        /// </summary>
        internal static string ArgumentEx_ChannelRange0_15 {
            get {
                return ResourceManager.GetString("ArgumentEx_ChannelRange0_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String must contain digits only..
        /// </summary>
        internal static string ArgumentEx_DigitStringOnly {
            get {
                return ResourceManager.GetString("ArgumentEx_DigitStringOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address must be between 0 and 1,023..
        /// </summary>
        internal static string ArgumentEx_I2cAddressRange {
            get {
                return ResourceManager.GetString("ArgumentEx_I2cAddressRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interval must be between 0 and 16,383 milliseconds..
        /// </summary>
        internal static string ArgumentEx_I2cInterval {
            get {
                return ResourceManager.GetString("ArgumentEx_I2cInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum pulse width must be between 0 and 16,383 milliseconds..
        /// </summary>
        internal static string ArgumentEx_MaxPulseWidth {
            get {
                return ResourceManager.GetString("ArgumentEx_MaxPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum pulse width is greater than maximum pulse width..
        /// </summary>
        internal static string ArgumentEx_MinMaxPulse {
            get {
                return ResourceManager.GetString("ArgumentEx_MinMaxPulse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum pulse width must be between 0 and 16,383 milliseconds..
        /// </summary>
        internal static string ArgumentEx_MinPulseWidth {
            get {
                return ResourceManager.GetString("ArgumentEx_MinPulseWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be negative..
        /// </summary>
        internal static string ArgumentEx_NoNegativeValue {
            get {
                return ResourceManager.GetString("ArgumentEx_NoNegativeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to String argument can not be null or empty..
        /// </summary>
        internal static string ArgumentEx_NotNullOrEmpty {
            get {
                return ResourceManager.GetString("ArgumentEx_NotNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin number must be between 0 and 127..
        /// </summary>
        internal static string ArgumentEx_PinRange0_127 {
            get {
                return ResourceManager.GetString("ArgumentEx_PinRange0_127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin must be between 0 and 7..
        /// </summary>
        internal static string ArgumentEx_PinRange0_7 {
            get {
                return ResourceManager.GetString("ArgumentEx_PinRange0_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port number must be between 0 and 15..
        /// </summary>
        internal static string ArgumentEx_PortRange0_15 {
            get {
                return ResourceManager.GetString("ArgumentEx_PortRange0_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be greater than zero..
        /// </summary>
        internal static string ArgumentEx_PositiveValue {
            get {
                return ResourceManager.GetString("ArgumentEx_PositiveValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sampling interval must be between 0 and 16,383 milliseconds..
        /// </summary>
        internal static string ArgumentEx_SamplingInterval {
            get {
                return ResourceManager.GetString("ArgumentEx_SamplingInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be between 0 and 16,383..
        /// </summary>
        internal static string ArgumentEx_ValueRange0_16383 {
            get {
                return ResourceManager.GetString("ArgumentEx_ValueRange0_16383", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value must be betwen 0 and 255..
        /// </summary>
        internal static string ArgumentEx_ValueRange0_255 {
            get {
                return ResourceManager.GetString("ArgumentEx_ValueRange0_255", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin is not supported..
        /// </summary>
        internal static string InvalidOpEx_PinNotSupported {
            get {
                return ResourceManager.GetString("InvalidOpEx_PinNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid serial port.
        /// </summary>
        internal static string InvalidSerialPort {
            get {
                return ResourceManager.GetString("InvalidSerialPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commandbyte 0x{0:X} is not implemented..
        /// </summary>
        internal static string NotImplementedEx_Command {
            get {
                return ResourceManager.GetString("NotImplementedEx_Command", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Response message code 0x{0:X} is not supported..
        /// </summary>
        internal static string NotSupportedResponse {
            get {
                return ResourceManager.GetString("NotSupportedResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The command parsing buffer is full..
        /// </summary>
        internal static string OverflowEx_CmdBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_CmdBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received message queue is full..
        /// </summary>
        internal static string OverflowEx_MsgBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_MsgBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The received strings buffer is full..
        /// </summary>
        internal static string OverflowEx_StringBufferFull {
            get {
                return ResourceManager.GetString("OverflowEx_StringBufferFull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait condition for {0} message timed out..
        /// </summary>
        internal static string TimeoutEx_WaitMessage {
            get {
                return ResourceManager.GetString("TimeoutEx_WaitMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait condition for string read in {0} mode timed out..
        /// </summary>
        internal static string TimeoutEx_WaitStringRequest {
            get {
                return ResourceManager.GetString("TimeoutEx_WaitStringRequest", resourceCulture);
            }
        }
    }
}
